name: configurator
description: "config your config"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.3.9
  fluent_ui: ^4.9.0
  font_awesome_flutter: 10.7.0
  url_launcher: ^6.3.0
  hugeicons: ^0.0.7
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  # 文件选择组件
  file_selector: ^1.0.3
  shared_preferences: ^2.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner:
  custom_lint:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true
  fonts:
    - family: moji
      fonts:
        - asset: fonts/NicoMoji-Regular.ttf

flutter_icons:
  windows:
    generate: true
    image_path: "assets/images/icon.png"
  linux:
    generate: true
    image_path: "assets/images/icon.png"
  macos:
    generate: true
    image_path: "assets/images/icon.png"
  web:
    generate: true
    image_path: "assets/images/icon.png"
flutter_intl:
  enabled: true